/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 06-Nov-2012, 09:03:22
 */

package timer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author w1387769
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitValue = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        showDigit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AddOne = new javax.swing.JButton();
        oneSecsDisplay = new javax.swing.JButton();
        oneSecs = new javax.swing.JTextField();
        showOneSecs = new javax.swing.JButton();
        oneSecsDisplay2 = new javax.swing.JButton();
        showOneSecs2 = new javax.swing.JButton();
        oneSecs2 = new javax.swing.JTextField();
        stop = new javax.swing.JButton();
        startTimer = new javax.swing.JButton();
        oneSecsDisplay3 = new javax.swing.JButton();
        oneSecs3 = new javax.swing.JTextField();
        showOneSecs3 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        oneSecsDisplay4 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        oneSecs4 = new javax.swing.JTextField();
        showOneSecs4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Timer");
        getContentPane().setLayout(null);

        digitValue.setText("0");
        digitValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitValueActionPerformed(evt);
            }
        });
        getContentPane().add(digitValue);
        digitValue.setBounds(570, 10, 50, 21);

        jTextField1.setBackground(new java.awt.Color(153, 0, 0));
        jTextField1.setText("                      ");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(410, 20, 70, 21);

        jTextField2.setBackground(new java.awt.Color(153, 0, 0));
        jTextField2.setText("  ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(390, 40, 20, 50);

        jTextField3.setBackground(new java.awt.Color(153, 0, 0));
        jTextField3.setText("  ");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(480, 40, 20, 60);

        jTextField4.setBackground(new java.awt.Color(153, 0, 0));
        jTextField4.setText("            ");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(410, 90, 70, 21);

        jTextField5.setBackground(new java.awt.Color(153, 0, 0));
        jTextField5.setText("  ");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(390, 110, 20, 50);

        jTextField6.setBackground(new java.awt.Color(153, 0, 0));
        jTextField6.setText("  ");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(480, 110, 20, 50);

        jTextField7.setBackground(new java.awt.Color(153, 0, 0));
        jTextField7.setText("           ");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(410, 160, 70, 21);

        showDigit.setText("show the digit");
        showDigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDigitActionPerformed(evt);
            }
        });
        getContentPane().add(showDigit);
        showDigit.setBounds(560, 50, 120, 27);

        jLabel1.setText("Digit");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 30, 25, 17);

        AddOne.setText("Add 1");
        AddOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOneActionPerformed(evt);
            }
        });
        getContentPane().add(AddOne);
        AddOne.setBounds(560, 80, 120, 27);

        oneSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecsDisplay);
        oneSecsDisplay.setBounds(500, 230, 160, 180);

        oneSecs.setText("0");
        oneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecs);
        oneSecs.setBounds(520, 420, 40, 21);

        showOneSecs.setText("Seconds");
        showOneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneSecsActionPerformed(evt);
            }
        });
        getContentPane().add(showOneSecs);
        showOneSecs.setBounds(560, 420, 84, 20);

        oneSecsDisplay2.setText(" ");
        oneSecsDisplay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplay2ActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecsDisplay2);
        oneSecsDisplay2.setBounds(340, 230, 160, 180);

        showOneSecs2.setText("Tens");
        showOneSecs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneSecs2ActionPerformed(evt);
            }
        });
        getContentPane().add(showOneSecs2);
        showOneSecs2.setBounds(380, 420, 62, 20);

        oneSecs2.setText("0");
        oneSecs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecs2ActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecs2);
        oneSecs2.setBounds(340, 420, 40, 21);

        stop.setText("End/Stop Timer");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop);
        stop.setBounds(560, 140, 120, 27);

        startTimer.setText("start");
        startTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimerActionPerformed(evt);
            }
        });
        getContentPane().add(startTimer);
        startTimer.setBounds(560, 110, 120, 27);

        oneSecsDisplay3.setText(" ");
        oneSecsDisplay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplay3ActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecsDisplay3);
        oneSecsDisplay3.setBounds(180, 230, 150, 180);

        oneSecs3.setText("0");
        oneSecs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecs3ActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecs3);
        oneSecs3.setBounds(190, 420, 60, 21);

        showOneSecs3.setText("Minutes");
        showOneSecs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneSecs3ActionPerformed(evt);
            }
        });
        getContentPane().add(showOneSecs3);
        showOneSecs3.setBounds(250, 420, 79, 20);

        jTextField8.setText(" ");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(150, 90, 60, 21);

        jButton1.setText("Real Time");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(161, 60, 100, 27);

        jTextField9.setText(" ");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(220, 90, 63, 21);

        jTextField10.setText(":");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(210, 90, 10, 21);

        jTextField11.setText("111");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(620, 210, 40, 21);

        jTextField12.setText("111");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(470, 210, 30, 21);

        jTextField13.setText("111");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(300, 210, 30, 21);

        jTextField14.setText(":");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(330, 230, 10, 180);

        oneSecsDisplay4.setText(" ");
        oneSecsDisplay4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplay4ActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecsDisplay4);
        oneSecsDisplay4.setBounds(40, 230, 140, 180);

        jTextField15.setText("111");
        getContentPane().add(jTextField15);
        jTextField15.setBounds(110, 210, 30, 21);

        oneSecs4.setText("0");
        getContentPane().add(oneSecs4);
        oneSecs4.setBounds(40, 420, 60, 21);

        showOneSecs4.setText("Minutes");
        showOneSecs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneSecs4ActionPerformed(evt);
            }
        });
        getContentPane().add(showOneSecs4);
        showOneSecs4.setBounds(100, 420, 79, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDigitActionPerformed
int digit1= Integer.parseInt(digitValue.getText());
if (digit1 == 0) {
    jTextField1.setVisible(true);
    jTextField2.setVisible(true);
    jTextField3.setVisible(true);
    jTextField4.setVisible(false);
    jTextField5.setVisible(true);
    jTextField6.setVisible(true);
    jTextField7.setVisible(true);
}
if (digit1 == 1){
    jTextField1.setVisible(false);
    jTextField2.setVisible(false);
    jTextField3.setVisible(true);
    jTextField4.setVisible(false);
    jTextField5.setVisible(false);
    jTextField6.setVisible(true);
    jTextField7.setVisible(false);
}
if (digit1 ==2){
    jTextField1.setVisible(true);
    jTextField2.setVisible(false);
    jTextField3.setVisible(true);
    jTextField4.setVisible(true);
    jTextField5.setVisible(true);
    jTextField6.setVisible(false);
    jTextField7.setVisible(true);
}
if (digit1 ==3){
    jTextField1.setVisible(true);
    jTextField2.setVisible(false);
    jTextField3.setVisible(true);
    jTextField4.setVisible(true);
    jTextField5.setVisible(false);
    jTextField6.setVisible(true);
    jTextField7.setVisible(true);
}
if (digit1 ==4){
     jTextField1.setVisible(false);
    jTextField2.setVisible(true);
    jTextField3.setVisible(true);
    jTextField4.setVisible(true);
    jTextField5.setVisible(false);
    jTextField6.setVisible(true);
    jTextField7.setVisible(false);
}
if (digit1 ==5){
     jTextField1.setVisible(true);
    jTextField2.setVisible(true);
    jTextField3.setVisible(false);
    jTextField4.setVisible(true);
    jTextField5.setVisible(false);
    jTextField6.setVisible(true);
    jTextField7.setVisible(true);
}
if (digit1 ==6){
     jTextField1.setVisible(true);
    jTextField2.setVisible(true);
    jTextField3.setVisible(false);
    jTextField4.setVisible(true);
    jTextField5.setVisible(true);
    jTextField6.setVisible(true);
    jTextField7.setVisible(true);
}
if (digit1 ==7){
     jTextField1.setVisible(true);
    jTextField2.setVisible(false);
    jTextField3.setVisible(true);
    jTextField4.setVisible(false);
    jTextField5.setVisible(false);
    jTextField6.setVisible(true);
    jTextField7.setVisible(false);
}
if (digit1 ==8){
     jTextField1.setVisible(true);
    jTextField2.setVisible(true);
    jTextField3.setVisible(true);
    jTextField4.setVisible(true);
    jTextField5.setVisible(true);
    jTextField6.setVisible(true);
    jTextField7.setVisible(true);
}
if (digit1 ==9){
     jTextField1.setVisible(true);
    jTextField2.setVisible(true);
    jTextField3.setVisible(true);
    jTextField4.setVisible(true);
    jTextField5.setVisible(false);
    jTextField6.setVisible(true);
    jTextField7.setVisible(true);
}













        // TODO add your handling code here:
    }//GEN-LAST:event_showDigitActionPerformed

    private void AddOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOneActionPerformed
int digit1= Integer.parseInt(digitValue.getText());
int x= Integer.parseInt(oneSecs.getText());
int y= Integer.parseInt(oneSecs2.getText());
int b= Integer.parseInt(oneSecs3.getText());
int m= Integer.parseInt(oneSecs4.getText());
int uu= Integer.parseInt(jTextField13.getText());
int yy= Integer.parseInt(jTextField12.getText());
int oo= Integer.parseInt(jTextField11.getText());
int pp= Integer.parseInt(jTextField15.getText());


if ((uu==b)&&(yy==y)&&(oo==x)&&(pp==b)){
stopActionPerformed(evt);}
else
{ digit1=digit1+1;
if ((digit1==10)){
                x=x+1;
digit1=0;}
if (x==10){
    y=y+1;
    x=0;}
if (y==6){
    b=b+1;
    y=0;}
  if (b==10){
      m=m+1;
  b=0;}


String ttt=Integer.toString(m);
oneSecs4.setText(ttt);

    String ee=Integer.toString(b);
oneSecs3.setText(ee);
String ss=Integer.toString(digit1);
digitValue.setText(ss);

String aa=Integer.toString(x);
oneSecs.setText(aa);
String bb=Integer.toString(y);
oneSecs2.setText(bb);
showDigitActionPerformed(evt);
showOneSecsActionPerformed(evt);
showOneSecs2ActionPerformed(evt);
showOneSecs3ActionPerformed(evt);}
showOneSecs4ActionPerformed(evt);




    }//GEN-LAST:event_AddOneActionPerformed

    private void oneSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplayActionPerformed
oneSecsDisplay.setIcon(new javax.swing.ImageIcon("0.JPG"));     // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsDisplayActionPerformed

    private void oneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsActionPerformed

    }//GEN-LAST:event_oneSecsActionPerformed

    private void showOneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneSecsActionPerformed
int ones=Integer.parseInt(oneSecs.getText());
if (ones==0) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("0.JPG"));
if (ones==1) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("1.JPG"));
if (ones==2) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("2.JPG"));
if (ones==3) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("3.JPG"));
if (ones==4) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("4.JPG"));
if (ones==5) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("5.JPG"));
if (ones==6) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("6.JPG"));
if (ones==7) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("7.JPG"));
if (ones==8) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("8.JPG"));
if (ones==9) oneSecsDisplay.setIcon(new javax.swing.ImageIcon("9.JPG"));
 // TODO add your handling code here:
    }//GEN-LAST:event_showOneSecsActionPerformed

    private void digitValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitValueActionPerformed

    }//GEN-LAST:event_digitValueActionPerformed

    private void oneSecsDisplay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplay2ActionPerformed
oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("0.JPG"));        // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsDisplay2ActionPerformed

    private void showOneSecs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneSecs2ActionPerformed
int ones=Integer.parseInt(oneSecs2.getText());
if (ones==0) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("0.JPG"));
if (ones==1) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("1.JPG"));
if (ones==2) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("2.JPG"));
if (ones==3) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("3.JPG"));
if (ones==4) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("4.JPG"));
if (ones==5) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("5.JPG"));
if (ones==6) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("6.JPG"));
if (ones==7) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("7.JPG"));
if (ones==8) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("8.JPG"));
if (ones==9) oneSecsDisplay2.setIcon(new javax.swing.ImageIcon("9.JPG"));         // TODO add your handling code here:
    }//GEN-LAST:event_showOneSecs2ActionPerformed

    private void oneSecs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecs2ActionPerformed



    }//GEN-LAST:event_oneSecs2ActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
this.dispose();
System.exit(0);
    }//GEN-LAST:event_stopActionPerformed

    private void startTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimerActionPerformed
javax.swing.Timer tm = new javax.swing.Timer(100, new ActionListener() { public void actionPerformed(ActionEvent evt)
{AddOneActionPerformed(evt);
}
});
tm.start();
    }//GEN-LAST:event_startTimerActionPerformed

    private void oneSecsDisplay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplay3ActionPerformed
oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("0.JPG"));         // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsDisplay3ActionPerformed

    private void showOneSecs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneSecs3ActionPerformed
int ones=Integer.parseInt(oneSecs3.getText());
if (ones==0) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("0.JPG"));
if (ones==1) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("1.JPG"));
if (ones==2) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("2.JPG"));
if (ones==3) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("3.JPG"));
if (ones==4) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("4.JPG"));
if (ones==5) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("5.JPG"));
if (ones==6) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("6.JPG"));
if (ones==7) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("7.JPG"));
if (ones==8) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("8.JPG"));
if (ones==9) oneSecsDisplay3.setIcon(new javax.swing.ImageIcon("9.JPG"));         // TODO add your handling code here:
    }//GEN-LAST:event_showOneSecs3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
   

    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     DateFormat dateFormat = new SimpleDateFormat("HH");
    Date time= new Date();
    dateFormat.format(time);
    jTextField8.setText(dateFormat.format(time));
    DateFormat dateFormat1 = new SimpleDateFormat("mm");
    Date time1= new Date();
    dateFormat1.format(time);
    jTextField9.setText(dateFormat1.format(time1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void oneSecsDisplay4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplay4ActionPerformed
oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("0.JPG"));          // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsDisplay4ActionPerformed

    private void oneSecs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecs3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneSecs3ActionPerformed

    private void showOneSecs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneSecs4ActionPerformed
int ones=Integer.parseInt(oneSecs4.getText());
if (ones==0) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("0.JPG"));
if (ones==1) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("1.JPG"));
if (ones==2) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("2.JPG"));
if (ones==3) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("3.JPG"));
if (ones==4) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("4.JPG"));
if (ones==5) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("5.JPG"));
if (ones==6) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("6.JPG"));
if (ones==7) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("7.JPG"));
if (ones==8) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("8.JPG"));
if (ones==9) oneSecsDisplay4.setIcon(new javax.swing.ImageIcon("9.JPG"));        // TODO add your handling code here:
    }//GEN-LAST:event_showOneSecs4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOne;
    private javax.swing.JTextField digitValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField oneSecs;
    private javax.swing.JTextField oneSecs2;
    private javax.swing.JTextField oneSecs3;
    private javax.swing.JTextField oneSecs4;
    private javax.swing.JButton oneSecsDisplay;
    private javax.swing.JButton oneSecsDisplay2;
    private javax.swing.JButton oneSecsDisplay3;
    private javax.swing.JButton oneSecsDisplay4;
    private javax.swing.JButton showDigit;
    private javax.swing.JButton showOneSecs;
    private javax.swing.JButton showOneSecs2;
    private javax.swing.JButton showOneSecs3;
    private javax.swing.JButton showOneSecs4;
    private javax.swing.JButton startTimer;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables

}
